import {
  IconBaby,
  IconBattery,
  IconCake,
  IconCare,
  IconCoffee,
  IconCookie,
  IconFish,
  IconGorcery,
  IconHome,
  IconSnowflake,
  IconUser,
  IconWheat,
} from "../assets/icons/InterfaceIcons";

export const CATEGORIES_DATA = [
  {
    id: "fruits-vegetables",
    label: "Fruits & Vegetables",
    icon: IconGorcery,

    subMenu: [
      {
        title: "Fresh Fruits",
        items: [
          "Fresh Fruits",
          "Fresh Vegetables",
          "Exotic Fruits & Veggies",
          "Organic Produce",
          "Herbs & Seasonings",
        ],
      },
      {
        title: "Fresh Fruits",
        items: [
          "Fresh Fruits",
          "Fresh Vegetables",
          "Exotic Fruits & Veggies",
          "Organic Produce",
          "Herbs & Seasonings",
        ],
      },
      {
        title: "Fresh Fruits",
        items: [
          "Fresh Fruits",
          "Fresh Vegetables",
          "Exotic Fruits & Veggies",
          "Organic Produce",
          "Herbs & Seasonings",
        ],
      },
      {
        title: "Fresh Fruits",
        items: [
          "Fresh Fruits",
          "Fresh Vegetables",
          "Exotic Fruits & Veggies",
          "Organic Produce",
          "Herbs & Seasonings",
        ],
      },
      {
        title: "Fresh Fruits",
        items: [
          "Fresh Fruits",
          "Fresh Vegetables",
          "Exotic Fruits & Veggies",
          "Organic Produce",
          "Herbs & Seasonings",
        ],
      },
      {
        title: "Fresh Fruits",
        items: [
          "Fresh Fruits",
          "Fresh Vegetables",
          "Exotic Fruits & Veggies",
          "Organic Produce",
          "Herbs & Seasonings",
        ],
      },
      {
        title: "Fresh Fruits",
        items: [
          "Fresh Fruits",
          "Fresh Vegetables",
          "Exotic Fruits & Veggies",
          "Organic Produce",
          "Herbs & Seasonings",
        ],
      },
    ],
  },
  {
    id: "dairy-bakery",
    label: "Dairy & Bakery",
    icon: IconCake,
    items: [
      "Milk",
      "Cheese",
      "Paneer",
      "Butter & Margarine",
      "Yogurt & Curd",
      "Bread & Buns",
      "Cakes & Muffins",
      "Cookies & Rusk",
    ],
  },
  // {
  //   id: "beverages",
  //   label: "Beverages",
  //   icon: IconCoffee,
  //   items: [
  //     "Tea",
  //     "Coffee",
  //     "Green Tea",
  //     "Soft Drinks",
  //     "Juices",
  //     "Energy Drinks",
  //     "Health Drinks",
  //     "Soda & Sparkling Water",
  //   ],
  // },
  // {
  //   id: "snacks",
  //   label: "Snacks & Branded Foods",
  //   icon: IconCookie,
  //   items: [
  //     "Chips & Namkeen",
  //     "Biscuits & Cookies",
  //     "Chocolates & Candies",
  //     "Dry Fruits & Nuts",
  //     "Breakfast Cereals",
  //     "Instant Noodles & Pasta",
  //     "Ketchup & Sauces",
  //     "Ready to Cook",
  //   ],
  // },
  {
    id: "staples",
    label: "Staples",
    icon: IconWheat,
    items: [
      "Rice",
      "Atta & Flours",
      "Dals & Pulses",
      "Cooking Oils & Ghee",
      "Salt & Sugar",
      "Spices & Masalas",
      "Dry Fruits",
      "Organic Staples",
    ],
  },
  {
    id: "personal-care",
    label: "Personal Care",
    icon: IconCare,
    items: [
      "Bath & Body",
      "Hair Care",
      "Oral Care",
      "Skin Care",
      "Men’s Grooming",
      "Women’s Hygiene",
    ],
  },
  // {
  //   id: "household",
  //   label: "Household Essentials",
  //   icon: IconHome,
  //   items: [
  //     "Detergents & Fabric Care",
  //     "Dishwashers",
  //     "Cleaners & Fresheners",
  //     "Tissues & Disposables",
  //     "Insect Repellents",
  //   ],
  // },
  {
    id: "baby-care",
    label: "Baby Care",
    icon: IconBaby,
    items: [
      "Baby Food",
      "Diapers & Wipes",
      "Baby Bath & Skin Care",
      "Feeding & Nursing",
      "Toys & Accessories",
    ],
  },
  {
    id: "meat-seafood",
    label: "Meat & Seafood",
    icon: IconFish,
    items: [
      "Fresh Chicken",
      "Fresh Mutton",
      "Fish & Seafood",
      "Cold Cuts",
      "Eggs",
    ],
  },
  // {
  //   id: "frozen-foods",
  //   label: "Frozen Foods",
  //   icon: IconSnowflake,
  //   items: [
  //     "Frozen Veggies",
  //     "Frozen Snacks",
  //     "Ice Creams",
  //     "Frozen Meat",
  //     "Ready Meals",
  //   ],
  // },
];
